name: LambdaTest Local Website CI/CD

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'   # Every 5 minutes

jobs:
  lambdatest-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Install Selenium
      - name: Install Selenium
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      # 4. Start local server for your website (adjust folder if needed)
      - name: Start Local Server
        run: |
          cd ./   # Change to the folder where index.html is
          python -m http.server 5500 &
          sleep 5  # Give server time to start

      # 5. Start LambdaTest Tunnel
      - name: Start LambdaTest Tunnel
        run: |
          wget https://downloads.lambdatest.com/tunnel/v4.0.382/LT_V4.zip -O LT_V4.zip
          unzip LT_V4.zip -d LT_Tunnel
          chmod +x LT_Tunnel/LT
          LT_Tunnel/LT --user ${{ secrets.jyotiyadav }} --key ${{ secrets.LT_QADsSrkYtrtgR0gOQKfoxZuVqQTm1DXlbHy0Vo9JkOzJwpe }} --daemon --tunnel-name LambdaTunnel
          sleep 10  # Wait for tunnel initialization

      # 6. Run Selenium tests
      - name: Run Selenium Tests
        run: python tunnel.py

      # 7. Stop LambdaTest Tunnel
      - name: Stop LambdaTest Tunnel
        run: pkill -f LT
