name: LambdaTest Local Website CI/CD

on:
  push:
    branches:
      - main
  # Uncomment this if you also want to run every 5 minutes automatically:
  # schedule:
  #   - cron: '*/5 * * * *'

jobs:
  lambdatest-tests:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
      # 1. Checkout repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Setup Python 3.11
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Install dependencies
      - name: Install Dependencies
        run: pip install selenium

      # 4. Start local server on port 5500
      - name: Start Local Server
        shell: pwsh
        run: |
          Start-Process python -ArgumentList "-m", "http.server", "5500"
          Write-Host "✅ Local server started at http://127.0.0.1:5500"
          Start-Sleep -Seconds 5

      # 5. Start LambdaTest Tunnel (✅ fixed for Windows)
      - name: Start LambdaTest Tunnel
        shell: pwsh
        run: |
          $TUNNEL_DIR = "LT_Tunnel"
          $TUNNEL_ZIP = "LT_Windows.zip"
          $TUNNEL_EXEC = "$TUNNEL_DIR/LT.exe"
          $PID_FILE = "$TUNNEL_DIR/lt_tunnel.pid"

          # Download and unzip tunnel binary
          New-Item -ItemType Directory -Force -Path $TUNNEL_DIR | Out-Null
          Invoke-WebRequest -Uri "https://downloads.lambdatest.com/tunnel/v3/windows/64bit/LT_Windows.zip" -OutFile $TUNNEL_ZIP
          Expand-Archive -Path $TUNNEL_ZIP -DestinationPath $TUNNEL_DIR -Force

          # Start the tunnel using Start-Process to avoid PowerShell parsing issues
          $args = "--user ${{ secrets.jyotiyadav }} --key ${{ secrets.LT_QADsSrkYtrtgR0gOQKfoxZuVqQTm1DXlbHy0Vo9JkOzJwpe }} --daemon --verbose --tunnel-name fd722dc5-4ba2-43b6-85e8-77ffd3f42d0c --pid-file $PID_FILE"
          Start-Process -FilePath $TUNNEL_EXEC -ArgumentList $args
          Write-Host "⏳ Starting LambdaTest Tunnel..."

          # Wait until the tunnel is ready (PID file check)
          # $maxWait = 30
          for ($i = 1; $i -le $maxWait; $i++) {
            if (Test-Path $PID_FILE) {
              Write-Host "✅ LambdaTest Tunnel is up and running."
              break
            }
            Start-Sleep -Seconds 1
            if ($i -eq $maxWait) {
              Write-Host "❌ Tunnel did not start within $maxWait seconds."
              exit 1
            }
          }

      # 6. Run your Selenium tests (they should target localhost)
      - name: Run Selenium Tests
        run: python tunnel.py

      # 7. Stop LambdaTest Tunnel after job
      - name: Stop LambdaTest Tunnel
        if: always()
        shell: pwsh
        run: |
            taskkill /F /IM LT.exe -ErrorAction SilentlyContinue
            Write-Host "🧹 LambdaTest Tunnel stopped (if it was running)."

