name: LambdaTest Local Website CI/CD

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes

jobs:
  lambdatest-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Install Dependencies (Selenium)
      - name: Install Dependencies
        run: pip install selenium

      # 4. Start local server
      # The server runs in the background (&) and requires a brief pause to start.
      - name: Start Local Server
        run: |
          python -m http.server 5500 &
          echo "Local server started on port 5500."
          sleep 5

      # 5. Start LambdaTest Tunnel (CRITICAL STEP)
      - name: Start LambdaTest Tunnel
        run: |
          TUNNEL_EXEC="LT_Tunnel/LT"
          PID_FILE="LT_Tunnel/lt_tunnel.pid"

          # 5a. Download and setup the tunnel executable
          wget https://downloads.lambdatest.com/tunnel/v4.0.382/LT_V4.zip -O LT_V4.zip
          unzip LT_V4.zip -d LT_Tunnel
          chmod +x $TUNNEL_EXEC
          
          # 5b. Start the tunnel in background with verbose logging
          # **Ensure secrets.LT_USERNAME and secrets.LT_ACCESS_KEY are set in GitHub**
          ./$TUNNEL_EXEC \
            --user ${{ secrets.jyotiyadav }} \
            --key ${{ secrets.LT_QADsSrkYtrtgR0gOQKfoxZuVqQTm1DXlbHy0Vo9JkOzJwpe }} \
            --daemon \
            --verbose \
            --tunnel-name LambdaTunnel \
            --pid-file $PID_FILE
          
          # 5c. Wait for the tunnel connection to confirm stability
          echo "Waiting for tunnel connection (max 20s)..."
          for i in $(seq 1 20); do 
            if [ -f $PID_FILE ]; then
              echo "LambdaTest Tunnel connected and ready (PID file found)."
              break
            fi
            sleep 1
            if [ $i -eq 20 ]; then
              echo "Error: LambdaTest Tunnel failed to connect within 20 seconds. CHECK LOGS FOR AUTHENTICATION FAILURE."
              exit 1 # Fail the step if tunnel doesn't start
            fi
          done

      # 6. Run Selenium tests
      - name: Run Selenium Tests
        run: python tunnel.py

      # 7. Stop LambdaTest Tunnel
      # 'if: always()' ensures cleanup runs even if the tests (Step 6) fail.
      # If Step 5 failed, pkill will exit with code 1, which is fine here.
      - name: Stop LambdaTest Tunnel
        if: always() 
        run: pkill -f LT